root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main cmd/main.go"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl"]

exclude_dir = ["assets", "tmp", "vendor"]
log = "air.log"

[screen]
clear_on_rebuild = true
keep_scroll = true
